/**
 * Biblioteca de contenido — Reporte de Nombre
 * Números 1 al 9, con cuatro aspectos por número.
 * Se registra en window.BIBLIOTECA_NOMBRE para que app.js lo consuma.
 */
window.BIBLIOTECA_NOMBRE = {
  "1": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desarrollar independencia, iniciativa y confianza para abrir su propio camino. Desde pequeño tenderá a explorar, tomar la delantera y buscar hacer las cosas a su manera, mostrando una energía creativa y emprendedora que disfruta descubrir nuevas posibilidades.\n\nComo padres, será valioso ofrecerle espacios donde pueda tomar pequeñas decisiones, experimentar y aprender de sus propios intentos. Cuando se siente escuchado y respetado, esta energía suele transformarse en liderazgo positivo, seguridad interior y una sana capacidad para confiar en sí mismo.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse libre para expresar quién es. Su mundo interior buscará autonomía, autenticidad y la satisfacción de descubrir que puede lograr cosas por sí mismo, sin dejar de sentirse amado y acompañado.\n\nPodrán fortalecer esta energía reconociendo sus esfuerzos más que sus resultados y animándolo a confiar en sus propias capacidades. Saber que puede intentar, equivocarse y volver a empezar le ayudará a construir una autoestima sólida desde sus primeros años.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien con presencia, iniciativa y una personalidad que transmite seguridad. Incluso desde pequeño podría proyectar una actitud decidida que inspire confianza y haga que otros lo identifiquen como alguien dispuesto a dar el primer paso.\n\nCon una guía amorosa aprenderá que la verdadera fortaleza también incluye escuchar, colaborar y valorar las ideas de quienes lo rodean. Así, esa imagen de liderazgo se expresará con cercanía, generosidad y equilibrio.",
    "potenciador": "Esta vibración fortalece su capacidad para confiar en sí mismo y desarrollar el valor de iniciar nuevos caminos. Actúa como un impulso que le recuerda que muchas de sus mayores fortalezas aparecerán cuando se atreva a dar el primer paso con entusiasmo y determinación.\n\nComo padres, pueden potenciar esta energía celebrando su iniciativa, permitiéndole asumir pequeños retos acordes a su edad y transmitiéndole la confianza de que siempre contará con ustedes mientras aprende. Cuando esta vibración se desarrolla en equilibrio, favorece una personalidad segura, creativa y capaz de convertir las ideas en acciones."
  },
  "2": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desenvolverse con sensibilidad, empatía y una especial capacidad para conectar con quienes lo rodean. De manera natural tenderá a observar antes de actuar, percibir los estados de ánimo de los demás y buscar ambientes donde reine la armonía y la cooperación.\n\nComo padres, será importante brindarle un entorno donde se sienta escuchado, valorado y emocionalmente seguro. Cuando aprende que su sensibilidad es una fortaleza, esta energía florece en forma de comprensión, paciencia y una gran capacidad para crear vínculos profundos y sinceros.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse querido, aceptado y parte de relaciones donde exista confianza y cercanía. Su corazón encontrará bienestar cuando perciba que puede expresar lo que siente sin miedo a ser juzgado o rechazado.\n\nPodrán fortalecer esta energía validando sus emociones y enseñándole que la sensibilidad no es una debilidad, sino una forma especial de comprender el mundo. Con ese acompañamiento desarrollará una seguridad emocional que le permitirá relacionarse desde la calma y el equilibrio.",
    "comoLoPercibiran": "Quienes conozcan a tu bebé probablemente lo perciban como alguien amable, tranquilo y fácil de querer. Su forma de relacionarse transmitirá cercanía y una disposición natural para colaborar, escuchar y generar ambientes agradables.\n\nA medida que crezca, será beneficioso animarlo a expresar también sus propias opiniones y necesidades. Así aprenderá que puede ser amable sin dejar de poner límites, desarrollando relaciones sanas donde el respeto sea mutuo.",
    "potenciador": "Esta vibración fortalece su capacidad para construir relaciones basadas en la empatía, la cooperación y el entendimiento. Cuando se encuentra en equilibrio, le ayuda a convertirse en un puente entre las personas, aportando calma, conciliación y una presencia que inspira confianza.\n\nComo padres, pueden potenciar esta energía enseñándole a valorar tanto a los demás como a sí mismo. Cuando descubre que cuidar de otros también implica cuidar de su propio bienestar, sus talentos relacionales se desarrollan con mayor seguridad y plenitud."
  },
  "3": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a expresarse con alegría, creatividad y espontaneidad. Tendrá una inclinación natural por comunicar lo que siente, explorar nuevas ideas y contagiar entusiasmo a quienes lo rodean, encontrando en el juego y la imaginación una forma de descubrir el mundo.\n\nComo padres, será valioso ofrecerle espacios donde pueda crear, contar historias, hacer preguntas y expresar libremente sus emociones. Cuando siente que su voz es escuchada, esta energía florece en confianza, optimismo y una gran capacidad para inspirar a los demás.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse libre para compartir lo que lleva dentro. Su mundo interior buscará ser comprendido, reconocido y valorado por su autenticidad, disfrutando especialmente de aquellos momentos donde pueda mostrar su imaginación y creatividad.\n\nPodrán fortalecer esta energía animándolo a expresar tanto sus alegrías como sus emociones más difíciles, sin temor a ser juzgado. Saber que siempre habrá un espacio seguro para comunicarse le permitirá desarrollar una autoestima sana y una gran confianza en sí mismo.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien alegre, sociable y lleno de vitalidad. Su manera de comunicarse y relacionarse transmitirá cercanía, entusiasmo y una energía que suele iluminar el ambiente con naturalidad.\n\nCon una guía amorosa aprenderá que también existen momentos para escuchar, reflexionar y dar espacio a los demás. Así, su facilidad para expresarse se convertirá en una herramienta que fortalecerá sus relaciones y le permitirá conectar de forma aún más profunda.",
    "potenciador": "Esta vibración fortalece su capacidad para comunicar, crear e inspirar desde la autenticidad. Cuando se desarrolla en equilibrio, le ayuda a transformar sus ideas, emociones y talentos en formas de expresión que enriquecen tanto su propia vida como la de quienes lo rodean.\n\nComo padres, pueden potenciar esta energía celebrando su curiosidad, fomentando actividades artísticas, creativas o de comunicación, y recordándole que su forma única de ver el mundo tiene un gran valor. Al sentirse libre para expresarse, esta vibración se convierte en una de sus mayores fortalezas."
  },
  "4": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desarrollar constancia, responsabilidad y una forma de actuar tranquila y organizada. De manera natural buscará comprender cómo funcionan las cosas, disfrutando de los entornos donde existen rutinas, estabilidad y seguridad para crecer paso a paso.\n\nComo padres, será valioso acompañarlo con paciencia, respetando su propio ritmo y ayudándolo a construir hábitos que le den confianza. Cuando esta energía se siente respaldada, florece en perseverancia, compromiso y una gran capacidad para convertir sus sueños en realidades.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse seguro, protegido y saber que puede construir sobre bases firmes. Su mundo interior encontrará tranquilidad cuando perciba estabilidad en su entorno y relaciones donde pueda confiar plenamente.\n\nPodrán fortalecer esta energía ofreciéndole límites claros junto con mucho afecto, creando un ambiente predecible donde se sienta libre para crecer. Saber que siempre tiene un lugar seguro al cual volver le permitirá desarrollar una confianza profunda en sí mismo y en la vida.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien sereno, confiable y con una actitud que transmite estabilidad. A medida que crezca, podría destacar por cumplir lo que promete, actuar con responsabilidad y afrontar los desafíos con paciencia y dedicación.\n\nSerá importante recordarle que también hay espacio para la flexibilidad, el juego y la espontaneidad. Cuando aprende a combinar estructura con apertura, proyecta una imagen equilibrada que inspira seguridad sin perder la capacidad de disfrutar el momento.",
    "potenciador": "Esta vibración fortalece su capacidad para construir con paciencia todo aquello que realmente importa. Le ayuda a desarrollar disciplina, compromiso y la fortaleza necesaria para avanzar con constancia, incluso cuando los resultados no llegan de inmediato.\n\nComo padres, pueden potenciar esta energía reconociendo su esfuerzo tanto como sus logros y enseñándole que cada pequeño paso tiene valor. Cuando esta vibración se desarrolla en equilibrio, se convierte en el cimiento que sostiene sus talentos y le permite crecer con confianza, estabilidad y resiliencia."
  },
  "5": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a descubrir el mundo con curiosidad, entusiasmo y una gran capacidad de adaptación. De manera natural sentirá interés por explorar, hacer preguntas, vivir nuevas experiencias y aprender a través del movimiento, el juego y el descubrimiento.\n\nComo padres, será valioso ofrecerle un entorno donde pueda experimentar con seguridad, combinando libertad con límites claros. Cuando esta energía encuentra ese equilibrio, florece en creatividad, confianza y una gran facilidad para desenvolverse en los cambios que la vida le presente.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse libre para descubrir, aprender y vivir experiencias que amplíen su horizonte. Su mundo interior disfrutará de la variedad, la novedad y la sensación de que siempre hay algo nuevo por conocer.\n\nPodrán fortalecer esta energía permitiéndole explorar a su ritmo y alentando su curiosidad con paciencia y acompañamiento. Cuando comprende que la verdadera libertad también implica responsabilidad, desarrolla una confianza que le permite crecer con equilibrio y entusiasmo.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien alegre, inquieto y lleno de energía. Su entusiasmo por descubrir cosas nuevas y su facilidad para adaptarse harán que transmita una sensación de vitalidad y espontaneidad que suele resultar contagiosa.\n\nCon una guía amorosa aprenderá que también existen momentos para detenerse, concentrarse y dar continuidad a lo que comienza. Así, esa imagen de dinamismo se complementará con perseverancia, permitiéndole aprovechar al máximo todos sus talentos.",
    "potenciador": "Esta vibración fortalece su capacidad para crecer a través de las experiencias, los cambios y el aprendizaje constante. Le recuerda que cada situación nueva puede convertirse en una oportunidad para desarrollar recursos, ampliar su visión y descubrir nuevas fortalezas.\n\nComo padres, pueden potenciar esta energía brindándole experiencias variadas, fomentando su curiosidad y acompañándolo a transformar cada desafío en un aprendizaje. Cuando esta vibración se desarrolla en equilibrio, favorece una personalidad flexible, segura y abierta a las oportunidades que la vida le ofrece."
  },
  "6": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desarrollar una naturaleza amorosa, protectora y profundamente vinculada a quienes quiere. De manera natural tenderá a valorar la armonía, el cuidado y los pequeños gestos que fortalecen los lazos familiares, encontrando satisfacción en contribuir al bienestar de quienes lo rodean.\n\nComo padres, será valioso ofrecerle un hogar donde el cariño, el respeto y la cooperación sean parte de la vida cotidiana. Cuando esta energía se siente sostenida, florece en responsabilidad, generosidad y una gran capacidad para construir relaciones llenas de confianza.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse amado, seguro y parte de un entorno donde reine el afecto sincero. Su mundo interior encontrará paz cuando perciba que los vínculos importantes se construyen desde la comprensión, la cercanía y el apoyo mutuo.\n\nPodrán fortalecer esta energía recordándole que también es importante cuidar de sí mismo, además de cuidar a los demás. Cuando aprende a equilibrar el amor que entrega con el amor que recibe, desarrolla una autoestima sana y relaciones más armoniosas.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien cálido, amable y con una presencia que transmite tranquilidad. A medida que crezca, será común que inspire confianza y que otros encuentren en él una persona cercana, considerada y dispuesta a colaborar.\n\nCon una guía amorosa aprenderá que no necesita hacerse responsable de todo para sentirse valioso. Así, esa imagen de persona generosa se expresará desde el equilibrio, permitiéndole ayudar sin dejar de respetar sus propias necesidades.",
    "potenciador": "Esta vibración fortalece su capacidad para crear ambientes de amor, unión y bienestar. Actúa como una energía que favorece el desarrollo de la empatía, el compromiso y el deseo de construir relaciones estables y significativas.\n\nComo padres, pueden potenciar esta energía enseñándole que el verdadero cuidado nace del equilibrio entre dar y recibir. Cuando esta vibración se desarrolla plenamente, sus talentos para acompañar, inspirar y fortalecer a quienes ama se convierten en una de sus mayores fortalezas."
  },
  "7": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a observar el mundo con profundidad, curiosidad y una gran capacidad de reflexión. De manera natural tenderá a hacerse preguntas, disfrutar de los momentos de calma y buscar comprender el porqué de las cosas antes de actuar.\n\nComo padres, será valioso respetar sus tiempos, responder a su curiosidad y ofrecerle espacios donde pueda explorar, imaginar y aprender sin prisas. Cuando esta energía se siente comprendida, florece en sabiduría, intuición y una gran capacidad para desarrollar un pensamiento propio.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela encontrar sentido, comprender la vida y descubrir aquello que realmente le inspira. Su mundo interior disfrutará de los momentos de silencio, la observación y las experiencias que despierten su curiosidad y alimenten su deseo de aprender.\n\nPodrán fortalecer esta energía animándolo a hacer preguntas, explorar nuevas ideas y confiar en su propia intuición. Cuando siente que sus inquietudes son valoradas, desarrolla una seguridad interior que lo acompañará durante toda su vida.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien tranquilo, observador y con una madurez que llama la atención. A medida que crezca, podrá transmitir una imagen de serenidad y profundidad, prefiriendo muchas veces escuchar y comprender antes que hablar.\n\nCon una guía amorosa aprenderá que también es valioso compartir lo que piensa y siente con quienes le rodean. Así, esa apariencia reservada se complementará con una comunicación más abierta, fortaleciendo sus relaciones sin perder su esencia reflexiva.",
    "potenciador": "Esta vibración fortalece su capacidad para aprender, desarrollar su intuición y descubrir conocimientos que le permitan comprender mejor el mundo y a sí mismo. Le recuerda que muchas de sus mayores fortalezas surgirán cuando combine la observación con la experiencia.\n\nComo padres, pueden potenciar esta energía fomentando el amor por el aprendizaje, respetando sus momentos de introspección y acompañándolo a confiar tanto en su inteligencia como en su sensibilidad. Cuando esta vibración se desarrolla en equilibrio, favorece una personalidad serena, consciente y profundamente sabia."
  },
  "8": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desarrollar determinación, fortaleza y una capacidad natural para organizar, construir y convertir sus ideas en resultados. Desde pequeño podría mostrar iniciativa para asumir responsabilidades, resolver desafíos y avanzar con perseverancia hacia aquello que se propone.\n\nComo padres, será valioso enseñarle que el verdadero éxito no se mide solo por lo que consigue, sino también por la forma en que trata a las personas durante el camino. Cuando esta energía se desarrolla en equilibrio, florece en liderazgo, confianza y una gran capacidad para generar bienestar tanto para sí mismo como para quienes lo rodean.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela sentirse capaz, útil y saber que puede construir algo valioso con sus talentos. Su mundo interior buscará desarrollar fortaleza, autonomía y la satisfacción de ver que sus esfuerzos tienen un impacto positivo.\n\nPodrán fortalecer esta energía reconociendo su constancia, enseñándole a valorar el proceso además del resultado y recordándole que pedir ayuda también es una muestra de fortaleza. Así desarrollará una seguridad interior basada en la confianza y no únicamente en los logros.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien seguro, decidido y con una presencia que transmite firmeza. A medida que crezca, podría proyectar una imagen de liderazgo natural y de alguien que inspira confianza para asumir responsabilidades o tomar decisiones.\n\nCon una guía amorosa aprenderá que la sensibilidad, la empatía y la colaboración fortalecen aún más su liderazgo. De esta manera, proyectará una presencia cercana y equilibrada, capaz de influir positivamente en quienes lo rodean.",
    "potenciador": "Esta vibración fortalece su capacidad para materializar ideas, superar desafíos y desarrollar una relación sana con la responsabilidad, la abundancia y el liderazgo. Le recuerda que sus mayores logros surgirán cuando combine determinación con integridad y sensibilidad hacia los demás.\n\nComo padres, pueden potenciar esta energía enseñándole que el éxito verdadero también incluye disfrutar el camino, compartir, colaborar y actuar con valores. Cuando esta vibración se expresa en equilibrio, se convierte en una fuente de confianza, resiliencia y capacidad para construir una vida con propósito."
  },
  "9": {
    "formaDeSer": "Esta vibración impulsa a tu bebé a desarrollar una naturaleza generosa, compasiva y con una gran sensibilidad hacia quienes lo rodean. De manera natural tenderá a percibir el mundo desde una mirada amplia, mostrando empatía, creatividad y un profundo deseo de aportar algo positivo a los demás.\n\nComo padres, será valioso acompañarlo a expresar esa sensibilidad con equilibrio, enseñándole que también es importante cuidar de sí mismo. Cuando esta energía se desarrolla plenamente, florece en sabiduría, nobleza y una capacidad natural para inspirar con el ejemplo.",
    "deseosDelSer": "En lo más profundo, esta vibración anhela vivir en un mundo donde exista más amor, comprensión y armonía. Su mundo interior encontrará plenitud cuando sienta que puede compartir lo mejor de sí y contribuir, incluso con pequeños gestos, al bienestar de quienes le rodean.\n\nPodrán fortalecer esta energía ayudándolo a comprender que su bondad no significa cargar con los problemas de los demás. Cuando aprende a combinar compasión con límites saludables, desarrolla una fortaleza emocional que le permitirá seguir ofreciendo lo mejor de sí sin perder su propio equilibrio.",
    "comoLoPercibiran": "Las personas probablemente verán en tu bebé a alguien amable, sensible y con una presencia que transmite calidez. A medida que crezca, muchos podrán percibir en él una capacidad especial para escuchar, comprender y hacer sentir bien a quienes comparten su camino.\n\nCon una guía amorosa aprenderá que también puede expresar sus propias necesidades y opiniones con confianza. Así, esa imagen de persona generosa se complementará con una autoestima sólida, permitiéndole relacionarse desde el equilibrio y la autenticidad.",
    "potenciador": "Esta vibración fortalece su capacidad para desarrollar empatía, visión amplia y un profundo sentido de propósito. Le ayuda a integrar sus talentos desde una perspectiva generosa, recordándole que sus acciones, por pequeñas que parezcan, pueden tener un impacto positivo en la vida de otras personas.\n\nComo padres, pueden potenciar esta energía cultivando valores como la gratitud, la solidaridad y el respeto, mientras le enseñan la importancia de cuidar también de su propio bienestar. Cuando esta vibración se expresa en equilibrio, favorece una personalidad inspiradora, consciente y capaz de dejar una huella positiva allí donde vaya."
  }
};
